#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'
echo -e "#################################################################"
echo -e "############################# ${LP}LUPIN${NC} #############################"
echo -e "#################################################################"

./gradlew integrate --stacktrace -Psource=Lupinus-albus-description
./gradlew integrate --stacktrace -Psource=Lupinus-angustifolius-description

./gradlew integrate --stacktrace -Psource=Amiga.gnm1.F4NR
./gradlew integrate --stacktrace -Psource=Tanjil.gnm1.Qq0N

./gradlew integrate --stacktrace -Psource=Amiga.gnm1.ann1.3GKS
./gradlew integrate --stacktrace -Psource=Tanjil.gnm1.ann1.nnV9

./gradlew integrate --stacktrace -Psource=Tanjil.gnm1.syn.TwnC

./gradlew integrate --stacktrace -Psource=legume.genefam.fam1.M65K
./gradlew integrate --stacktrace -Psource=legume.genefam.fam1.M65K.trees_ML_rooted
./gradlew integrate --stacktrace -Psource=interpro
./gradlew integrate --stacktrace -Psource=interpro-go
./gradlew integrate --stacktrace -Psource=go
./gradlew integrate --stacktrace -Psource=so
./gradlew integrate --stacktrace -Psource=plant-ontology
./gradlew integrate --stacktrace -Psource=plant-trait-ontology
