#!/bin/sh

echo ""
echo "##########################################################################################################################################"
echo "##########################################################################################################################################"
echo "##################################################### LUPINMINE INTEGRATE ################################################################"
echo "##########################################################################################################################################"
echo "##########################################################################################################################################"
echo ""

## ontologies
./gradlew integrate -Psource=go --stacktrace
./gradlew integrate -Psource=so --stacktrace
./gradlew integrate -Psource=plant-ontology --stacktrace
./gradlew integrate -Psource=plant-trait-ontology --stacktrace

## InterPro
./gradlew integrate -Psource=interpro --stacktrace
./gradlew integrate -Psource=interpro-go --stacktrace

## LIS gene families
./gradlew integrate -Psource=legume.genefam.fam1.M65K --stacktrace
./gradlew integrate -Psource=legume.genefam.fam1.M65K.trees_ML_rooted --stacktrace

## lupal
./gradlew --stacktrace integrate -Psource=lupal-about

## lupal.Amiga
./gradlew --stacktrace integrate -Psource=Amiga.gnm1.F4NR
./gradlew --stacktrace integrate -Psource=Amiga.gnm1.ann1.3GKS.cds
./gradlew --stacktrace integrate -Psource=Amiga.gnm1.ann1.3GKS.gene_models_main
./gradlew --stacktrace integrate -Psource=Amiga.gnm1.ann1.3GKS.mRNA
./gradlew --stacktrace integrate -Psource=Amiga.gnm1.ann1.3GKS.protein
./gradlew --stacktrace integrate -Psource=Amiga.gnm1.ann1.3GKS.legfed_v1_0.M65K.gfa
./gradlew --stacktrace integrate -Psource=Amiga.gnm1.ann1.3GKS.legfed_v1_0.M65K.pathway

## lupan
./gradlew --stacktrace integrate -Psource=lupan-about

## lupan.Tangil
./gradlew --stacktrace integrate -Psource=Tanjil.gnm1.Qq0N
./gradlew --stacktrace integrate -Psource=Tanjil.gnm1.ann1.nnV9.cds
./gradlew --stacktrace integrate -Psource=Tanjil.gnm1.ann1.nnV9.gene_models_main
./gradlew --stacktrace integrate -Psource=Tanjil.gnm1.ann1.nnV9.legfed_v1_0.M65K.gfa
./gradlew --stacktrace integrate -Psource=Tanjil.gnm1.ann1.nnV9.pathway
./gradlew --stacktrace integrate -Psource=Tanjil.gnm1.ann1.nnV9.protein
