#!/bin/sh

## clear the logs (quietly)
rm -f intermine.log

# ## generally restore this from a dump first
# ./gradlew integrate -Psource=lupin-genotyping --stacktrace

## echo a big marker so we can see when this run started in the scroll
echo "##########################################################################################################################################"
echo "##########################################################################################################################################"
echo "########################################################## INTEGRATE #####################################################################"
echo "##########################################################################################################################################"
echo "##########################################################################################################################################"

# ## ontologies
# ./gradlew integrate -Psource=go --stacktrace
# ./gradlew integrate -Psource=so --stacktrace
# ./gradlew integrate -Psource=interpro --stacktrace
# ./gradlew integrate -Psource=interpro-go --stacktrace

# ## gene families : LIS datastore
# ./gradlew integrate -Psource=legume.genefam.fam1 --stacktrace

# ## lupal : LIS datastore
# ./gradlew integrate -Psource=lupal --stacktrace
# ./gradlew integrate -Psource=lupal.Amiga.gnm1-chromosome-fasta --stacktrace
# ./gradlew integrate -Psource=lupal.Amiga.gnm1.ann0-cds-fasta --stacktrace
# ./gradlew integrate -Psource=lupal.Amiga.gnm1.ann0-mrna-fasta --stacktrace
# ./gradlew integrate -Psource=lupal.Amiga.gnm1.ann0-protein-fasta --stacktrace
# ./gradlew integrate -Psource=lupal.Amiga.gnm1.ann0 --stacktrace
# ./gradlew integrate -Psource=lupal.Amiga.gnm1.ann0-gff --stacktrace

# ## lupan : LIS datastore
# ./gradlew integrate -Psource=lupan --stacktrace
# ./gradlew integrate -Psource=lupan.Tanjil.gnm1-chromosome-fasta --stacktrace
# ./gradlew integrate -Psource=lupan.Tanjil.gnm1.ann1-cds-fasta --stacktrace
# ./gradlew integrate -Psource=lupan.Tanjil.gnm1.ann1-protein-fasta --stacktrace
# ./gradlew integrate -Psource=lupan.Tanjil.gnm1.ann1 --stacktrace
# ./gradlew integrate -Psource=lupan.Tanjil.gnm1.ann1-gff --stacktrace
 
